module.exports = {
  session: 'https://api.weixin.qq.com/sns/jscode2session',
  token: 'https://api.weixin.qq.com/cgi-bin/token',
  send: 'https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send',
  customSend: 'https://api.weixin.qq.com/cgi-bin/message/custom/send',

  qrcode: 'https://api.weixin.qq.com/wxa/getwxacode',
  code: 'https://open.weixin.qq.com/connect/qrconnect',
  mediaUpload: 'https://api.weixin.qq.com/cgi-bin/media/upload',
  unifyPay: 'https://api.mch.weixin.qq.com/pay/unifiedorder',
  componentToken: 'https://api.weixin.qq.com/cgi-bin/component/api_component_token',
  preauthCode: 'https://api.weixin.qq.com/cgi-bin/component/api_create_preauthcode',
  authUrl: 'https://mp.weixin.qq.com/cgi-bin/componentloginpage',
  authToken: 'https://api.weixin.qq.com/cgi-bin/component/api_query_auth',
  refreshToken: 'https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token',
  compSession: 'https://api.weixin.qq.com/sns/component/jscode2session',
  modifyDomain: 'https://api.weixin.qq.com/wxa/modify_domain',
  bindTester: 'https://api.weixin.qq.com/wxa/bind_tester',
  unbindTester: 'https://api.weixin.qq.com/wxa/unbind_tester',
  uploaCode: 'https://api.weixin.qq.com/wxa/commit',
  getExpCode: 'https://api.weixin.qq.com/wxa/get_qrcode',
  getCategory: 'https://api.weixin.qq.com/wxa/get_category',
  getPage: 'https://api.weixin.qq.com/wxa/get_page',
  submitAudit: 'https://api.weixin.qq.com/wxa/submit_audit',
  getAuditStatus: 'https://api.weixin.qq.com/wxa/get_auditstatus',
  release: 'https://api.weixin.qq.com/wxa/release',
  changeVisit: 'https://api.weixin.qq.com/wxa/change_visitstatus'
}